window.GAME_MONITOR_ACTIVITIES = [
  {
    id: 'act-torchlight-20260413-00',
    date: '2026-04-13',
    game: '火炬之光：无限',
    gameId: 'torchlight-infinite',
    platform: '端游/手游',
    category: '版本更新',
    title: '官网新闻列表确认存在，可作为公告抓取入口样板',
    importance: 'high',
    summary: '已确认火炬官网存在 /us/news/list 新闻列表入口，可作为后续公告抓取和拆条的首个正式来源层。',
    sourcePlatform: '官网 / 新闻列表',
    sourceType: '公告入口验证',
    sourceUrl: 'https://torchlight.xd.com/us/news/list',
    capturedAt: '2026-04-13 15:34',
    freshness: 'today',
    todo: '已确认列表页存在分类结构（Featured / Announcement / Events）；下一步继续定位单条公告 URL 规律并拆出 2-3 条样板公告',
    owner: '大飞哥'
  },
  {
    id: 'act-torchlight-20260413-02',
    date: '2026-04-13',
    game: '火炬之光：无限',
    gameId: 'torchlight-infinite',
    platform: '端游/手游',
    category: '版本更新',
    title: '公告列表页已确认存在分类结构，可进入条目级拆解阶段',
    importance: 'high',
    summary: '通过直接抓取 HTML，已确认新闻列表页存在 Featured / Announcement / Events 分类结构，说明后续可继续尝试提取单条公告信息。',
    sourcePlatform: '官网 / 新闻列表 HTML',
    sourceType: '条目级拆解验证',
    sourceUrl: 'https://torchlight.xd.com/us/news/list',
    capturedAt: '2026-04-13 15:34',
    freshness: 'today',
    todo: '已识别出新闻 JSON 接口；下一步优先从 JSON 中拆 2-3 条公告样板并写回系统',
    owner: '大飞哥'
  },
  {
    id: 'act-torchlight-20260413-03',
    date: '2026-04-13',
    game: '火炬之光：无限',
    gameId: 'torchlight-infinite',
    platform: '端游/手游',
    category: '版本更新',
    title: '已识别火炬官网新闻 JSON 接口，可直接读取公告列表',
    importance: 'high',
    summary: '已从新闻列表页中定位到 API_GET_NEWS，并确认其实际 JSON 数据源为 website.xdcdn.net/form/website/torchlight/news.json，可直接读取新闻/活动列表。',
    sourcePlatform: '官网 / 新闻 JSON',
    sourceType: '结构化公告源验证',
    sourceUrl: 'https://website.xdcdn.net/form/website/torchlight/news.json',
    capturedAt: '2026-04-13 15:35',
    freshness: 'today',
    todo: '从 JSON 中优先拆出 2-3 条与赛季/活动相关的公告样板，写成真实公告流',
    owner: '大飞哥'
  },
  {
    id: 'act-torchlight-20260413-01',
    date: '2026-04-13',
    game: '火炬之光：无限',
    gameId: 'torchlight-infinite',
    platform: '端游/手游',
    category: '营销动作',
    title: 'SS12 金钞项目继续推进达人内容合作',
    importance: 'high',
    summary: '重点围绕金钞获取机制、回坑理由、中国美院共创三层信息展开达人传播。',
    sourcePlatform: '官网 / 官方站点 + 业务同步',
    sourceType: '官方来源样板',
    sourceUrl: 'https://torchlight.xd.com/',
    capturedAt: '2026-04-13 15:31',
    freshness: 'today',
    todo: '补充达人名单、发布日期和分平台投放节奏；后续从官网公告页继续细化到具体公告链接',
    owner: '大飞哥'
  },
  {
    id: 'act-torchlight-real-20250418-01',
    date: '2025-04-18',
    game: '火炬之光：无限',
    gameId: 'torchlight-infinite',
    platform: '端游/手游',
    category: '活动福利',
    title: '[Sandlord] Gold Rush Event Announcement',
    importance: 'high',
    summary: '真实公告摘要：可通过签到与赛季活动获取多次 Pactspirit 抽取机会、Activation Medium，并可通过刷图参与抽取纪念金钞。',
    sourcePlatform: '官网 / 新闻 JSON',
    sourceType: '真实公告样板',
    sourceUrl: 'https://torchlight.xd.com/en/news/single?id=pidg8uIC7DE6',
    capturedAt: '2026-04-14 10:55',
    freshness: 'stale',
    todo: '继续补充公告正文的完整机制拆解，并与 SS12 金钞传播链做映射',
    owner: '大飞哥',
    subType: 'Event Announcement',
    researchTag: '活动向'
  },
  {
    id: 'act-torchlight-real-20240419-01',
    date: '2024-04-19',
    game: '火炬之光：无限',
    gameId: 'torchlight-infinite',
    platform: '端游/手游',
    category: '活动福利',
    title: '[Whispering Mist] Event Announcement',
    importance: 'medium',
    summary: '真实公告摘要：可通过签到获取 Legendary Drop Pactspirit 相关奖励与 Activation Medium，并围绕赛季活动继续参与刷图与奖励获取。',
    sourcePlatform: '官网 / 新闻 JSON',
    sourceType: '真实公告样板',
    sourceUrl: 'https://torchlight.xd.com/en/news/single?id=1ffdcuamXC0B',
    capturedAt: '2026-04-14 10:55',
    freshness: 'stale',
    todo: '继续补该公告的完整正文拆解，并标注 Whispering Mist 赛季背景与活动机制',
    owner: '大飞哥',
    subType: 'Event Announcement',
    researchTag: '活动向'
  },
  {
    id: 'act-torchlight-real-20240419-02',
    date: '2024-04-19',
    game: '火炬之光：无限',
    gameId: 'torchlight-infinite',
    platform: '端游/手游',
    category: '活动福利',
    title: '[Whispering Mist] Boon Announcement',
    importance: 'medium',
    summary: '真实公告摘要：围绕 Legendary Drop Pactspirit、Activation Medium 与 Commemorative Gold Notes 等奖励机制展开，是典型的福利向公告样板。',
    sourcePlatform: '官网 / 新闻 JSON',
    sourceType: '真实公告样板',
    sourceUrl: 'https://torchlight.xd.com/en/news/single?id=b2u19uan4vtg',
    capturedAt: '2026-04-14 10:55',
    freshness: 'stale',
    todo: '继续补福利条款细节，并与同赛季活动公告做配对展示',
    owner: '大飞哥',
    subType: 'Boon Announcement',
    researchTag: '福利向'
  },
  {
    id: 'act-poe2-20260413-01',
    date: '2026-04-13',
    game: '流放之路2',
    gameId: 'path-of-exile-2',
    platform: '端游',
    category: '赛道对照',
    title: 'ARPG 核心用户讨论继续集中在深度与门槛平衡',
    importance: 'medium',
    summary: '适合与火炬之光：无限对照分析易入门叙事 vs 深度叙事如何影响传播。',
    sourcePlatform: '人工录入 / 竞品观察',
    sourceType: '赛道观察',
    sourceUrl: '',
    capturedAt: '2026-04-13 14:51',
    freshness: 'today',
    todo: '后续补核心讨论帖子与代表性视频链接',
    owner: '大飞哥'
  },
  {
    id: 'act-honorworld-20260413-01',
    date: '2026-04-13',
    game: '王者荣耀世界',
    gameId: 'honor-world',
    platform: '端游/手游',
    category: '预约/预热',
    title: '高关注新品进入物料与预期管理双重观察期',
    importance: 'high',
    summary: '后续需重点记录 PV 表现、评论关键词和测试节点前的舆情走向。',
    sourcePlatform: '人工录入 / 预约监控',
    sourceType: '新品观察',
    sourceUrl: '',
    capturedAt: '2026-04-13 14:51',
    freshness: 'today',
    todo: '补 PV 链接、测试节点和用户高频质疑点',
    owner: '大飞哥'
  },
  {
    id: 'act-delta-20260413-01',
    date: '2026-04-13',
    game: '三角洲行动',
    gameId: 'delta-force',
    platform: '端游/手游',
    category: '社区口碑',
    title: '玩家对版本内容与竞技环境持续讨论',
    importance: 'medium',
    summary: '适合跟踪其内容更新是否带动正向讨论，还是继续累积环境类抱怨。',
    sourcePlatform: '人工录入 / 社区观察',
    sourceType: '社区舆情',
    sourceUrl: '',
    capturedAt: '2026-04-13 14:51',
    freshness: 'today',
    todo: '补对应社区来源与代表性负反馈点',
    owner: '大飞哥'
  },
  {
    id: 'act-gfp-20260413-01',
    date: '2026-04-13',
    game: '和平精英',
    gameId: 'game-for-peace',
    platform: '手游',
    category: '营销动作',
    title: '成熟产品依旧保持高频活动与联动打法',
    importance: 'medium',
    summary: '值得持续拆解其活动包装、素材节奏和大众传播语言。',
    sourcePlatform: '人工录入 / 竞品观察',
    sourceType: '营销监控',
    sourceUrl: '',
    capturedAt: '2026-04-13 14:51',
    freshness: 'today',
    todo: '补活动名、联动对象和官方物料入口',
    owner: '大飞哥'
  },
  {
    id: 'act-valorant-20260413-01',
    date: '2026-04-13',
    game: '无畏契约',
    gameId: 'valorant',
    platform: '端游',
    category: '赛事/主播',
    title: '竞技内容与主播讨论继续拉动社区热度',
    importance: 'medium',
    summary: '重点观察版本平衡、赛事热点与内容创作者话题之间的联动。',
    sourcePlatform: '人工录入 / 内容观察',
    sourceType: '赛事内容',
    sourceUrl: '',
    capturedAt: '2026-04-13 14:51',
    freshness: 'today',
    todo: '补赛事节点与主播代表内容',
    owner: '大飞哥'
  },
  {
    id: 'act-honorchess-20260413-01',
    date: '2026-04-13',
    game: '王者万象棋',
    gameId: 'honor-chess',
    platform: '手游',
    category: '预约/预热',
    title: '新品玩法认知建立期，适合记录用户第一印象',
    importance: 'medium',
    summary: '需要重点观察用户到底是冲玩法来，还是主要由王者 IP 驱动关注。',
    sourcePlatform: '人工录入 / 预约监控',
    sourceType: '新品观察',
    sourceUrl: '',
    capturedAt: '2026-04-13 14:51',
    freshness: 'today',
    todo: '补宣传物料、预约福利与达人预热信息',
    owner: '大飞哥'
  },
  {
    id: 'act-oce-20260413-01',
    date: '2026-04-13',
    game: '失控进化',
    gameId: 'out-of-control-evolution',
    platform: '端游/手游',
    category: '定位观察',
    title: '题材与核心卖点仍在形成认知',
    importance: 'low',
    summary: '现阶段重点不是看绝对热度，而是看用户是否知道它是什么。',
    sourcePlatform: '人工录入 / 新品观察',
    sourceType: '产品定位',
    sourceUrl: '',
    capturedAt: '2026-04-13 14:51',
    freshness: 'today',
    todo: '补官方介绍与第一波传播切口',
    owner: '大飞哥'
  }
];
